/*
 * MainView.java
 *
 * Created on __DATE__, __TIME__
 */

package users;

import java.sql.SQLException;

import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

import model.*;

/**
 *
 * @author  __USER__
 */
public class MainView extends javax.swing.JFrame implements Runnable {

	/** Creates new form MainView */
	public MainView() {
		initComponents();
		Thread t = new Thread(this);
		t.start();
		this.setLocationRelativeTo(null);
	}

	public void lunbo() {
		for (int i = 1; i <= 5; i++) {
			this.jLabel2.setIcon(new ImageIcon("img/" + i + ".jpg"));
			try {
				Thread.sleep(1000);
			} catch (InterruptedException e) {
				// TODO Auto-generated catch block
				e.printStackTrace();
			}
			if (i == 5)
				i = 1;
		}
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	//GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		jPanel1 = new javax.swing.JPanel();
		jLabel1 = new javax.swing.JLabel();
		jTextField1 = new javax.swing.JTextField();
		jButton1 = new javax.swing.JButton();
		jButton2 = new javax.swing.JButton();
		jButton3 = new javax.swing.JButton();
		jButton4 = new javax.swing.JButton();
		jSeparator1 = new javax.swing.JSeparator();
		jButton5 = new javax.swing.JButton();
		jButton6 = new javax.swing.JButton();
		jButton7 = new javax.swing.JButton();
		jButton8 = new javax.swing.JButton();
		jButton9 = new javax.swing.JButton();
		jLabel2 = new javax.swing.JLabel();
		jButton10 = new javax.swing.JButton();
		jButton11 = new javax.swing.JButton();
		jButton12 = new javax.swing.JButton();
		jButton13 = new javax.swing.JButton();
		jButton14 = new javax.swing.JButton();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

		jPanel1.setBackground(new java.awt.Color(238, 255, 158));

		jLabel1.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 18));
		jLabel1.setText("\u4e00\u672c\u6b63\u7ecf\u5c0f\u8bf4\u7f51");

		jTextField1.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jTextField1ActionPerformed(evt);
			}
		});

		jButton1.setBackground(new java.awt.Color(250, 108, 47));
		jButton1.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 14));
		jButton1.setText("\u641c\u7d22");
		jButton1.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton1ActionPerformed(evt);
			}
		});

		jButton2.setBackground(new java.awt.Color(250, 108, 47));
		jButton2.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 14));
		jButton2.setText("\u767b\u5f55");
		jButton2.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton2ActionPerformed(evt);
			}
		});

		jButton3.setBackground(new java.awt.Color(250, 108, 47));
		jButton3.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 14));
		jButton3.setText("\u6ce8\u518c");
		jButton3.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton3ActionPerformed(evt);
			}
		});

		jButton4.setBackground(new java.awt.Color(250, 108, 47));
		jButton4.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 14));
		jButton4.setText("\u6211\u7684\u4e66\u67b6");
		jButton4.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton4ActionPerformed(evt);
			}
		});

		jButton5.setBackground(new java.awt.Color(250, 108, 47));
		jButton5.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 14));
		jButton5.setText("\u699c\u5355");
		jButton5.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton5ActionPerformed(evt);
			}
		});

		jButton6.setBackground(new java.awt.Color(250, 108, 47));
		jButton6.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 14));
		jButton6.setText("\u8bc4\u8bba");
		jButton6.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton6ActionPerformed(evt);
			}
		});

		jButton7.setBackground(new java.awt.Color(250, 108, 47));
		jButton7.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 14));
		jButton7.setText("\u4f5c\u8005\u4e13\u533a");
		jButton7.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton7ActionPerformed(evt);
			}
		});

		jButton8.setBackground(new java.awt.Color(250, 108, 47));
		jButton8.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 14));
		jButton8.setText("\u7ba1\u7406\u8005");
		jButton8.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton8ActionPerformed(evt);
			}
		});

		jButton9.setBackground(new java.awt.Color(250, 108, 47));
		jButton9.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 14));
		jButton9.setText("vip\u4e13\u533a");

		jButton10.setBackground(new java.awt.Color(250, 108, 47));
		jButton10.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 14));
		jButton10.setText("\u597d\u4e66\u63a8\u8350");

		jButton11.setBackground(new java.awt.Color(250, 108, 47));
		jButton11.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 14));
		jButton11.setIcon(new javax.swing.ImageIcon(
				"C:\\Users\\HP\\Desktop\\列子\\img\\全球高武.jpg")); // NOI18N
		jButton11.setBorder(null);
		jButton11.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton11ActionPerformed(evt);
			}
		});

		jButton12.setBackground(new java.awt.Color(250, 108, 47));
		jButton12.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 14));
		jButton12.setIcon(new javax.swing.ImageIcon(
				"C:\\Users\\HP\\Desktop\\列子\\img\\三寸人间.jpg")); // NOI18N
		jButton12.setBorder(null);
		jButton12.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton12ActionPerformed(evt);
			}
		});

		jButton13.setBackground(new java.awt.Color(250, 108, 47));
		jButton13.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 14));
		jButton13.setIcon(new javax.swing.ImageIcon(
				"C:\\Users\\HP\\Desktop\\列子\\img\\山村庄园主.jpg")); // NOI18N
		jButton13.setBorder(null);

		jButton14.setBackground(new java.awt.Color(250, 108, 47));
		jButton14.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 14));
		jButton14.setIcon(new javax.swing.ImageIcon(
				"C:\\Users\\HP\\Desktop\\列子\\img\\我有一枚建成令.jpg")); // NOI18N
		jButton14.setBorder(null);

		javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(
				jPanel1);
		jPanel1.setLayout(jPanel1Layout);
		jPanel1Layout
				.setHorizontalGroup(jPanel1Layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								javax.swing.GroupLayout.Alignment.TRAILING,
								jPanel1Layout
										.createSequentialGroup()
										.addContainerGap(160, Short.MAX_VALUE)
										.addComponent(
												jLabel1,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												143,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addGap(71, 71, 71)
										.addComponent(
												jTextField1,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												95,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(jButton1)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(jButton2)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(jButton3)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(jButton4).addGap(183,
												183, 183))
						.addGroup(
								jPanel1Layout
										.createSequentialGroup()
										.addComponent(
												jSeparator1,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												795,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addContainerGap(165, Short.MAX_VALUE))
						.addGroup(
								jPanel1Layout.createSequentialGroup().addGap(
										114, 114, 114).addComponent(jLabel2,
										javax.swing.GroupLayout.PREFERRED_SIZE,
										643,
										javax.swing.GroupLayout.PREFERRED_SIZE)
										.addContainerGap(203, Short.MAX_VALUE))
						.addGroup(
								javax.swing.GroupLayout.Alignment.TRAILING,
								jPanel1Layout.createSequentialGroup()
										.addContainerGap(424, Short.MAX_VALUE)
										.addComponent(jButton10).addGap(447,
												447, 447))
						.addGroup(
								jPanel1Layout
										.createSequentialGroup()
										.addGap(53, 53, 53)
										.addComponent(
												jButton11,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												203,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(
												jButton12,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												208,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(
												jButton13,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												201,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addGap(7, 7, 7)
										.addComponent(
												jButton14,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												189,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addContainerGap(81, Short.MAX_VALUE))
						.addGroup(
								jPanel1Layout
										.createSequentialGroup()
										.addGap(125, 125, 125)
										.addComponent(jButton5)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(jButton6)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(jButton7)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(jButton8)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(jButton9)
										.addContainerGap(432, Short.MAX_VALUE)));
		jPanel1Layout
				.setVerticalGroup(jPanel1Layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								jPanel1Layout
										.createSequentialGroup()
										.addGroup(
												jPanel1Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(
																jTextField1,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(jButton1)
														.addComponent(jButton2)
														.addComponent(jButton3)
														.addComponent(jButton4)
														.addComponent(
																jLabel1,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																39,
																javax.swing.GroupLayout.PREFERRED_SIZE))
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(
												jSeparator1,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												10,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addGroup(
												jPanel1Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(jButton5)
														.addComponent(jButton6)
														.addComponent(jButton7)
														.addComponent(jButton8)
														.addComponent(jButton9))
										.addGap(29, 29, 29)
										.addComponent(
												jLabel2,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												131,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(jButton10)
										.addGap(18, 18, 18)
										.addGroup(
												jPanel1Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addGroup(
																jPanel1Layout
																		.createParallelGroup(
																				javax.swing.GroupLayout.Alignment.BASELINE)
																		.addComponent(
																				jButton12,
																				javax.swing.GroupLayout.DEFAULT_SIZE,
																				270,
																				Short.MAX_VALUE)
																		.addComponent(
																				jButton13,
																				javax.swing.GroupLayout.DEFAULT_SIZE,
																				270,
																				Short.MAX_VALUE)
																		.addComponent(
																				jButton14,
																				javax.swing.GroupLayout.DEFAULT_SIZE,
																				270,
																				Short.MAX_VALUE))
														.addComponent(
																jButton11,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																270,
																Short.MAX_VALUE))
										.addContainerGap()));

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(
				getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addGroup(
				javax.swing.GroupLayout.Alignment.TRAILING,
				layout.createSequentialGroup().addContainerGap(
						javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
						.addComponent(jPanel1,
								javax.swing.GroupLayout.PREFERRED_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE,
								javax.swing.GroupLayout.PREFERRED_SIZE)
						.addContainerGap()));
		layout.setVerticalGroup(layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addGroup(
				layout.createSequentialGroup().addComponent(jPanel1,
						javax.swing.GroupLayout.DEFAULT_SIZE,
						javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
						.addContainerGap()));

		pack();
	}// </editor-fold>
	//GEN-END:initComponents

	private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
	}

	private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {
		new ReadingView().setVisible(true);
		// TODO add your handling code here:
	}

	private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {
		new Quan1().setVisible(true);
		// TODO add your handling code here:
	}

	private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {
		//new AdminView().setVisible(true);
		AdminView av = new AdminView();
		av.setVisible(true);
		// TODO add your handling code here:
	}

	private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {
		WriterView l = new WriterView();
		l.setVisible(true);

		// TODO add your handling code here:
	}

	private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {
		//User u = new User();
		CommentView l = new CommentView();
		l.setVisible(true);
		// TODO add your handling code here:
	}

	private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {
		RegisterView l = new RegisterView();
		l.setVisible(true);

		// TODO add your handling code here:
	}

	//搜索
	private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {
		//数据库请求
		Bookcontrol bocl = new Bookcontrol();
		String uname = jTextField1.getText();
		try {
			boolean flag = bocl.queryBook(uname);
			if (flag) {
				if ("三寸人间".equals(uname)) {
					CommentView c = new CommentView();
					c.setVisible(true);
				}else {
					JOptionPane.showMessageDialog(null, "存在在书籍，但未上线！", "",
							JOptionPane.WARNING_MESSAGE);
				}
			} else {
				JOptionPane.showMessageDialog(null, "未查找到书籍", "",
						JOptionPane.WARNING_MESSAGE);
			}

		} catch (Exception e) {
			e.printStackTrace();
		}

		// TODO add your handling code here:
	}

	//登录
	private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {
		LoginView l = new LoginView();
		l.setVisible(true);
		// TODO add your handling code here:
	}

	private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {
		RankinglistView l = new RankinglistView();
		l.setVisible(true);
		// TODO add your handling code here:
	}

	private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {
		Bookshelf l = new Bookshelf();
		l.setVisible(true);
		// TODO add your handling code here:
	}

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new MainView().setVisible(true);
			}
		});
	}

	//GEN-BEGIN:variables
	// Variables declaration - do not modify
	private javax.swing.JButton jButton1;
	private javax.swing.JButton jButton10;
	private javax.swing.JButton jButton11;
	private javax.swing.JButton jButton12;
	private javax.swing.JButton jButton13;
	private javax.swing.JButton jButton14;
	private javax.swing.JButton jButton2;
	private javax.swing.JButton jButton3;
	private javax.swing.JButton jButton4;
	private javax.swing.JButton jButton5;
	private javax.swing.JButton jButton6;
	private javax.swing.JButton jButton7;
	private javax.swing.JButton jButton8;
	private javax.swing.JButton jButton9;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JPanel jPanel1;
	private javax.swing.JSeparator jSeparator1;
	private javax.swing.JTextField jTextField1;

	// End of variables declaration//GEN-END:variables
	@Override
	public void run() {
		// TODO Auto-generated method stub
		lunbo();
	}

}